version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - "${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}"
  mongodb:
    image: mongo:latest
  server:
    build: .
    command: make s
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - elasticsearch
      - mongodb
    volumes:
      - .:/usr/src/app
