version: 2
jobs:
  build-and-test:
    docker:
      - image: artsy/hokusai
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run:
          name: Test
          command: hokusai test --build
  deploy-staging:
    docker:
      - image: artsy/hokusai
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Configure
          command: hokusai configure --kubectl-version 1.10.7 --s3-bucket artsy-citadel --s3-key k8s/config --platform linux
      - run:
          name: Push
          command: hokusai registry push --tag $CIRCLE_SHA1 --force --overwrite
      - run:
          name: Assets
          command: hokusai staging run --tag $CIRCLE_SHA1 --env S3_KEY=$S3_KEY --env S3_SECRET=$S3_SECRET --env COMMIT_HASH=$(git rev-parse --short HEAD) 'yarn assets && yarn bucket-assets -b positron-staging'
      - run:
          name: Deploy to staging
          command: hokusai staging deploy $CIRCLE_SHA1 --git-remote origin
      - run:
          name: Update staging git branch
          command: git push git@github.com:artsy/positron.git $CIRCLE_SHA1:staging --force
  deploy-production:
    docker:
      - image: artsy/hokusai
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Configure
          command: hokusai configure --kubectl-version 1.10.7 --s3-bucket artsy-citadel --s3-key k8s/config --platform linux
      - run:
          name: Push
          command: hokusai registry push --tag $CIRCLE_SHA1 --force --overwrite
      - run:
          name: Assets
          command: hokusai production run --tag $CIRCLE_SHA1 --env S3_KEY=$S3_KEY --env S3_SECRET=$S3_SECRET --env COMMIT_HASH=$(git rev-parse --short HEAD) 'yarn assets && yarn bucket-assets -b positron-production'
      - run:
          name: Deploy to production
          command: hokusai production deploy $CIRCLE_SHA1 --git-remote origin
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - staging
                - release
      - deploy-staging:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - deploy-production:
          filters:
            branches:
              only: release
