version: "2"
services:
  positron:
    command: ["yarn", "test"]
    extends:
      file: build.yml
      service: positron
    environment:
      - CI=true
      - ELASTICSEARCH_URL=http://positron-elasticsearch:9200
      - MONGOHQ_URL=mongodb://positron-mongodb:27017/positron-test
    env_file: ../.env.test
    depends_on:
      - positron-mongodb
      - positron-elasticsearch
  positron-elasticsearch:
    image: artsy/elasticsearch:2.1
    ports:
      - "9200:9200"
  positron-mongodb:
    image: mongo:4.0
    ports:
      - "27017:27017"
    command: ["--storageEngine=mmapv1", "--quiet", "--nojournal"]
